CANINSTITUTE2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('elearningplatform.urls'))
]
admin.site.site_header='CAN INSTITUTE ADMINISTRATION'
admin.site.site_title='CONTENT MANAGEMENT'

elearningplatform/urls.py
from django.urls import path
from.import views
app_name="elearningplatform"
urlpatterns= [ path("",views.home, name="home"),
             path("Note/",views.Notes,name='Notes'),
             path('helpcipse/',views.helpcipse, name='helpcipse'),
             path("video/",views.Videos, name="video"),
             path('register/',views.registerPage,name='register'),
             path('About/',views.About ,name='About'),
             path('Article/',views.Article,name='Article'),
             path('certificatecourse/',views.certificatecourses,name='certificatecourses'),
             path('diplomacourses/',views.diplomacourses,name='diplomacourses'),
             path('undergraduatecourses/',views.undergraduatecourses,name='undergraduatecourses'),
             path('postgraduatecourses/',views.postgraduatecourses,name='postgraduatecourses'),
             path('professionalcourses/',views.professionalcourses,name='professionalcourses'),
             path('quizz/',views.quizz,name='quizz'),
             path('login/', views.loginPage,name='login'),
             path('logout/', views.logoutPage,name='logout'),
            # path('coursemenu/',views.coursemenu,name='coursemenu'),
             
             path('Learningmaterials/',views.Learning_materials,name='LearningMaterials'),
             path ('privacypolicy/',views.PrivacyPolicy,name='Privacy Policy'),
             ]

elearningplatform/models.py
from django.db import models
class Multichoice(models.Model):
    pass
class Articles2(models.Model):
    title=models.CharField(max_length=100)
    textdata=models.CharField(max_length=5000)
    def __str__(self):
        return self.textdata
class Videotutorial(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    title=models.CharField(max_length=50)
    videoclip=models.URLField(max_length=500)
    def __str__(self):
        return self.title
class Add_Questions(models.Model):
    Question = models.CharField(max_length=20000,null=True, unique=True)
    A = models.CharField(max_length=20000,null=True, blank=True)
    B = models.CharField(max_length=20000,null=True,blank=True)
    C = models.CharField(max_length=20000,null=True,blank=True)
    D = models.CharField(max_length=20000,null=True,blank=True)
    E=models.CharField(max_length=20000, null=True,blank=True)
    Answer = models.CharField(max_length=20000,null=True ,blank=True)
    Answer_expalanation=models.CharField(max_length=20000,null=True,blank=True)
    
    def __str__(self):
        return self.Question
        
    

# Create your models here.

elearningplatform/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class createuserform(UserCreationForm):
    class meta:
        model=User
        fields=['username','password','email']

elearningplatform/views.py
from django.shortcuts import redirect,render
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth import login, logout,authenticate
from .forms import *

from .models import *
from django.contrib.auth.decorators import login_required
def home(request):
     videoobj=Videotutorial.objects.all()
     context={'videoobj':videoobj}
     return render(request,'caninstitutehome.html',context)
#def coursemenu(request):
 #   return render(request, 'coursemenu.html')

def quizz(request):
    question=Add_Questions.objects.all()
           
    paginator=Paginator(question,50)
    page = request.GET.get('page', 1)
    try:
          users = paginator.page(page)
    except PageNotAnInteger:
          users = paginator.page(1)
    except EmptyPage:
           users = paginator.page(paginator.num_page)
    if request.method == 'POST':
        
        score=0
        wrong=0
        correct=0
        total=0
        question_number=1
        for q in users:
            total+=1
            question_number+=1
            
            
            if q.Answer ==  request.POST.get(q.Question):
                score+=10
                correct+=1
            else:
                wrong+=1
        percent = score/(total*10) *100
        time=request.POST.get('timer')
        context = {
            'users':users,
            'score':score,
            'time': request.POST.get('timer'),
            'correct':correct,
            'wrong':wrong,
            'percent':percent,
            'total':total
        }
        
        
        return render(request,'results.html',context)
    else:
        
        return render(request,'multichoice.html',{'users': users})
def certificatecourses(request):
   
    return render(request,'certificatecourses.html')
def helpcipse(request):
    return render(request,'helpcipse.html')

def diplomacourses(request):
    return render(request,'diplomacourses.html')
def undergraduatecourses(request):
    return render(request,'undergraduatecourses.html')
def postgraduatecourses(request):
    return render(request,'postgraduatecourse.html')
def professionalcourses(request):
    return render(request,'professionalcourses.html')
def Notes(request):
    return(request,'cansinstitute.html')
def Videos(request):
    videoobj=Videotutorial.objects.all()
    context={'videoobj':videoobj}
    return(request,'caninstitutevideo.html',context)
def Register(request):
    return(request,'caninstitute.html')
def About(request):
    pass
def Article(request):
    
    articles=Articles2.objects.all()
    context={'articles':articles}
    return render(request,'caninstitutearticle.html',context)

def Learning_materials(request):
    return render(request,'multichoice.html')
def PrivacyPolicy(request):
    pass
def registerPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form=createuserform()
        if request.method =='POST':
            form=createuserform(request.POST)
            if form.is_valid():
             user= form.save()
            return redirect('elearningplatform:login')
        context={'form':form}
        return render(request,'register.html', context)
def loginPage(request):
    if request.user.is_authenticated:
        return redirect('elearningplatform:home')
    else:
       if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('/')
       context={}
       return render(request,'login.html',context)
 
def logoutPage(request):
    logout(request)
    return redirect('/')    


    

elearningplatform/templates/caninstitutearticle.html
{% extends 'caninstitute.html'%}
{% block content %}
{% for articles in articles %}
           <h1 style="font: size 30px;; font-family: Times New Roman;"> {{articles.title}} </h1>
           <hr>
           
            <p style="font-size: 20px;font-family: Gill Sans;">{{articles.textdata}} </p>
         {% endfor %}
{% endblock %}

elearningplatform/templates/caninstitutehome.html
{% extends 'caninstitute.html' %}

{% load static%}

{% block content %}

<style type="text/css">
    * {
        box-sizing: border-box;

    }
    .image-container{
        margin: 0 auto;
        width: 50%;
        box-shadow: 0 15px 30px  rgba(0,0,0,0.30),0 11px 8px rgba(0,0,0,0.22);
        margin-bottom: 20px;
        transition-duration: 3s;
    }
    .image-container:hover{
        width: 90%;
        box-shadow: 0 18px 36px rgba(0,0,0,0.30),0 14px 11px rgba(0,0, 0, 0.22);

    }
    img{
        width: 100%;
        height: auto;
    }
    .image-description{
        padding: 0 15px 15px 15px;
        text-align: center;
        font-family: Georgia;
        
    }
    .lightbox{
        display: table;
        transition-duration: 3s;
        position: fixed;
        top: 300%;
        width: 70%;
        height: 70%;
        background: rgba(0,0, 0, 0.7);

    }
    .lightbox:target{
        top: 0;
    }
    .lightbox-content{
        display:table-cell;
        vertical-align: middle;
        text-align: center;
    }
    .close{
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 20px;
        font-weight: 300;
        text-decoration: none;
        color: rgb(175, 29, 29);
    }
    .lightbox img{
        max-width: 100%;
        height: auto;
    }

</style>
<h1 style="text-align: center;"> GALLERY</h1>
<div class="gallery">
    <div class="image-container"id="container1">
        <a href="#image1">
            <img src="{% static 'web2.jpg' %}" alt="">
        </a>
        <p class="image-decription">MEET INDUSTRIES EXPERTS</p>
    </div>
    <div class="image-container"id="container2">
        <a href="#image2">
            <img src="{% static 'emmy.webp'%}" alt=""> -->
        </a>
        <p class="image-decription">GET MENTORS</p>
    </div>
    <div class="image-container"id="container3">
        <a href="#image3">
            <img src="{% static 'emmy2.jpg' %}" alt="">
        </a>
        <p class="image-decription">LEVEL UP YOUR SKILLS</p>
    </div>
</div>
<div class="lightbox" id="image1">
    <a href="#" class="close">CLOSE</a>
    <div class="lightbox-content">
        <img src="{% static 'web2.jpg' %}" alt="">
    </div>
</div>
<div class="lightbox" id="image2">
    <a href="#" class="close">CLOSE</a>
    <div class="lightbox-content">
        <img src="{% static 'emmy.webp' %}" alt="">
    </div>
</div>
<div class="lightbox" id="image3">
    <a href="#" class="close">CLOSE</a>
    <div class="lightbox-content">
        <img src="{% static 'emmy2.jpg' %}" alt="">
    </div>
</div>


{% endblock %}

elearningplatform/templates/caninstitutevideo.html
{% extends 'caninstitute.html'%}
{% block video %}
<h1>WATCH VIDEOS</h1>
<hr>

<video src="video.mp4" controls ></video>

{% endblock %}

elearningplatform/templates/certificatecourses.html
{% extends 'caninstitute.html'%}
{% block content%}
<style type="text/css">
table {
    border-collapse:collapse;
    color:white;
    font-family:sans_serif;
    width: 750px;
}
table,th,td {
    border:1px solid black;
    text-align:center;
}
th,td {
    padding:25px;
}
tr:nth-child(odd){
    background:#173459;
}
tr:nth-child(even){
    background:#903c56;
}
</style>
<p> <h1>CERTIFICATES COURSES</h1></p>

<table>
    <thead>
        <tr>
            <th>COURSE NAME</th>
            <th>COURSE DURATION</th>
            <th>FEE STRUCTURE</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td><h3>Certificate in Cooperative Business Administration</h3></td>
            <td>2 years</td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>National Certificate in Business Studies</h3> </td>
            <td><h3>2 years</h3></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>National Certificate in Accountancy</h3></td>
            <td><h3>2 years</h3></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        
    </tbody>
</table>

{% endblock %}

elearningplatform/templates/coursemenu.html
{% extends 'caninstitute.html'%}
{% block content %}
  <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
 <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <style>
      *{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Lato', sans-serif;
  font-family: 'Oswald', sans-serif;
}
.wrapper{
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  /*background: linear-gradient(-135deg, #c850c0, #4158d0);*/
  /* background: linear-gradient(375deg, #1cc7d0, #2ede98); */
 /* background: linear-gradient(-45deg, #e3eefe 0%, #efddfb 100%);*/
  /* clip-path: circle(25px at calc(0% + 45px) 45px); */
  background: #000;
  clip-path: circle(25px at calc(100% - 45px) 45px);
  transition: all 0.3s ease-in-out;
}
#active:checked ~ .wrapper{
  clip-path: circle(75%);
}
.menu-btn{
  position: absolute;
  z-index: 2;
  right: 20px;
  /* left: 20px; */
  top: 20px;
  height: 50px;
  width: 50px;
  text-align: center;
  line-height: 50px;
  border-radius: 50%;
  font-size: 20px;
  color: #fff;
  cursor: pointer;
  /*background: linear-gradient(-135deg, #c850c0, #4158d0);*/
  /* background: linear-gradient(375deg, #1cc7d0, #2ede98); */
 /* background: linear-gradient(-45deg, #e3eefe 0%, #efddfb 100%); */
  background: #000;
  transition: all 0.3s ease-in-out;
}
#active:checked ~ .menu-btn{
  color: #fff;
}
#active:checked ~ .menu-btn i:before{
  content: "\f00d";
}
.wrapper ul{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  list-style: none;
  text-align: center;
}
.wrapper ul li{
  margin: 15px 0;
}
.wrapper ul li a{
  color: none;
  text-decoration: none;
  font-size: 30px;
  font-weight: 500;
  padding: 5px 30px;
  color: #fff;
  border-radius: 50px;
  background: #000;
  position: relative;
  line-height: 50px;
  transition: all 0.3s ease;
}
.wrapper ul li a:after{
  position: absolute;
  content: "";
  background: #fff;
   background: linear-gradient(#14ffe9, #ffeb3b, #ff00e0);
  /*background: linear-gradient(375deg, #1cc7d0, #2ede98);*/
  width: 104%;
  height: 110%;
  left: -2%;
  top: -5%; /* if the font is 'Oswald'*/
  border-radius: 50px;
  transform: scaleY(0);
  z-index: -1;
  animation: rotate 1.5s linear infinite;
  transition: transform 0.3s ease;
}
.wrapper ul li a:hover:after{
  transform: scaleY(1);
}
.wrapper ul li a:hover{
  color: #fff;
}
input[type="checkbox"]{
  display: none;
}
.content{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: -1;
  text-align: center;
  width: 100%;
  color: #202020;
}
.content .title{
  font-size: 40px;
  font-weight: 700;
}
.content p{
  font-size: 35px;
  font-weight: 600;
}

@keyframes rotate {
  0%{
    filter: hue-rotate(0deg);
  }
  100%{
    filter: hue-rotate(360deg);
  }
}

    </style>
  </head>

  <body>
    <input type="checkbox" id="active">
    <label for="active" class="menu-btn"><i class="fas fa-bars"></i></label>
    <div class="wrapper">
      <ul>
<li><a href="#">PROJECT MANAGEMENT PROFESSIONALS ASSESSMENTS</a></li>
<li><a href="#">CPA</a></li>
<li><a href="#">Services</a></li>
<li><a href="#">Gallery</a></li>
<li><a href="#">Feedback</a></li>
</ul>
</div>
<div class="content">
      <div class="title">
Fullscreen Overlay Navigation Bar</div>
<p>
with HTML & CSS Neon Effect</p>
</div>
</body>

{% endblock%}

elearningplatform/templates/diplomacourses.html
{% extends 'caninstitute.html'%}
{% block content%}
<style type="text/css">
table {
    border-collapse:collapse;
    color:white;
    font-family:sans_serif;
    width: 750px;
}
table,th,td {
    border:1px solid black;
    text-align:center;
}
th,td {
    padding:25px;
}
tr:nth-child(odd){
    background:#173459;
}
tr:nth-child(even){
    background:#903c56;
}
</style>
<p> <h1>DIPLOMA COURSES</h1></p>

<table>
    <thead>
        <tr>
            <th>COURSE NAME</th>
            <th>COURSE DURATION</th>
            <th>FEE STRUCTURE</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td><h3>National Diploma in Accountancy</h3></td>
            <td><h3>2 years</h3></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>National Diploma in M arketing</h3></td>
            <td><h3>2 years</h3></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Uganda Diploma in Business Studies</h3></td>
            <td><h3>2 years</h3></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        
    </tbody>
</table>

{% endblock %}

elearningplatform/templates/helpcipse.html
{% extends 'caninstitute.html'%}
<style type="style/css">
    .help {
        width: 600px;
        height: 900px;
       
    }
</style>
<div class="help">
    <p><h2>HELP CAN INSTITUTE OF PROFESSIONAL STUDIES</h2></p>
    
</div>

elearningplatform/templates/login.html
{% extends 'caninstitute.html' %}
{% load static%}
{% block content %}
<div class="container jumbotron">
    <form method="POST" action="">
        {% csrf_token %}
        <p><input type="text" name="username" placeholder="Username..."></p>
        <p><input type="password" name="password" placeholder="Password..." ></p>
        <input class="btn btn-success" type="submit" value="Login">
        <p>Do not have an account<a href='{% url 'elearningplatform:register' %}'>Register</a></p>
    </form>
</div>
{% endblock %}

elearningplatform/templates/multichoice.html
{% extends 'caninstitute.html' %}
 
{% block content %}
{% load static %}
<style  type="text/css">
  .container{
    font-size: 20px;
    text-emphasis-color: rgb(217, 217, 255) ;
    font-family: 'Times New Roman';
    background-color: rgb(245, 244, 255);
    font-weight: 200;
  }
  .form-group{
    font-weight: bold;
    margin: 20px;
    padding: 15px;
    box-shadow: 0 5px  10px 0 rgba(0,0,00.3),0 7px 21px 0 rgba(0,0,0,0.20);
    
  }
  .form-check {
    display:flow-root;
    margin-bottom: 15px;
  }
  .button {
    padding: 15px;
    border: 2px;
    color: blue;
  }
</style>


<div class="container "><center>
<h1><hr>PROJECT MANAGEMENT PROFESSIONAL ASSESSMENTS</h1>
</center>
<div align="right " id="displaytimer"><b> <h1>Timer: 0 Minutes </h1></b></div>
 
 <form method='post' action=''>
    {% csrf_token %}
    {% for q  in users %}
    {{x}}
       
    <div class="form-group">
      <label for="question"> {{q.Question}}</label>
    </div>
    <br>
    <div class="form-check">
        <div class="form-check">
           <input class="form-check-input" type="radio"  name="{{q.Question}}" id="gridRadios1" value="{{q.A}}" checked>
            
            <label class="form-check-label" for="gridRadios1" bg-secondary-subtle >
                A.{{q.A}}
            </label>
            
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.Question}}" id="gridRadios2" value="{{q.B}}">
            <label class="form-check-label" for="gridRadios2">
                B.{{q.B}}
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.Question}}" id="gridRadios1" value="{{q.C}}">
            <label class="form-check-label" for="gridRadios1">
               C. {{q.C}}
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.Question}}" id="gridRadios2" value="{{q.D}}">
            <label class="form-check-label" for="gridRadios2">
               D. {{q.D}}
            </label>
        </div>
        <br>
        <br>
        <br>
        <hr color="back";>
    </div> 
       
    
    {% endfor %}

  

    <input id='timer' type='hidden' name="timer" value="">
    <br>
    <button type="submit" class="btn btn-primary">SUBMIT TEST FOR TEST RESULTS</button>
  </form>
      {% if users.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
  
  
    {% block script %}
        <script>
 
            /*consol.log('Are You Ready to Take Online Assessment')*/
            const timer=document.getElementById('displaytimer')
            console.log(timer.textContent)
            const inputtag = document.getElementById('timer')
 
            t=0
            setInterval(()=>{
                t+=1
                timer.innerHTML ="<b>Timer: " +t+" Minutes</b>"
                inputtag.value = t
            },6000)
        </script>
    {% endblock script %}
 
</div>



{% endblock %}

elearningplatform/templates/postgraduatecourse.html
{% extends 'caninstitute.html'%}
{% block content%}
<style type="text/css">
table {
    border-collapse:collapse;
    color:white;
    font-family:sans_serif;
    width: 750px;
}
table,th,td {
    border:1px solid black;
    text-align:center;
}
th,td {
    padding:25px;
}
tr:nth-child(odd){
    background:#173459;
}
tr:nth-child(even){
    background:#903c56;
}
</style>
<p> <h1>POSTGRADUATE COURSES</h1></p>

<table>
    <thead>
        <tr>
            <th>COURSE NAME</th>
            <th>COURSE DURATION</th>
            <th>FEE STRUCTURE</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td><h3>Postgraduate Diploma in Project Mangement</h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Postgraduate Diploma in Management </h3>
            </td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Postgraduate Diploma in M&E </h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Postgraduate Diploma in HRM </h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Postgraduate Diploma in Financial Management </h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td> <h3>Postgraduate Diploma in Public Sector Management </h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        
    </tbody>
</table>

{% endblock %}

elearningplatform/templates/professionalcourses.html
{% extends 'caninstitute.html'%}
{% block content%}
<style type="text/css">
table {
    border-collapse:collapse;
    color:white;
    font-family:sans_serif;
    width: 750px;
}
table,th,td {
    border:1px solid black;
    text-align:center;
}
th,td {
    padding:25px;
}
tr:nth-child(odd){
    background:#173459;
}
tr:nth-child(even){
    background:#903c56;
}
</style>
<p> <h1>PROFESSIONAL COURSES</h1></p>

<table>
    <thead>
        <tr>
            <th>COURSE NAME</th>
            <th>COURSE DURATION</th>
            <th>FEE STRUCTURE</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td> <h3>1.Project Management Professional (PMP) sponsored by Project Management Institute of USA</h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><p><h3>Accounting</h3></p> <p><li>CPA(U)( ICPAU Certificate)</li></p><p><li>ACCA(UK bases certificate sponsored by APMG)</li></p></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><p><h3> Project In a Controlled Environtment(PRINCE") UK based PM Certificate</h3></p>
                <p><li>PRINCE2 Foundation</li></p><p><li>PRINCE2 Practioners</li></p>
            </td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Project Risk Management Professional</h3></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><p><h3>Procurement</h3></p><p><li>CIPS(Level 1-6)-(UK based Certificate)</li></p></td>
            <td></td>
            <td></td>
            
        </tr>
        <tr>
            <td><h3>Chartered Institute of Maarketing(CIM)</h3></td>
            <td></td>
            <td></td>
            
        </tr>
        
        
    </tbody>
</table>

{% endblock %}

elearningplatform/templates/register.html
{% extends 'caninstitute.html'%}
{% block content %}
<style>
.register{
    background-color:rgb(233, 233, 238);
    align-self:center;
}
</style>
<div class="register">
<form action="" method="post">
    {% csrf_token %}
{{form.as_p}}
<input type="submit">
</form>
</div>
{% endblock %}

elearningplatform/templates/results.html

{% extends 'caninstitutehome.html' %}
{% load static %}
 
{% block content %}
<style type="text/css">
    .container{
        background-color: rgb(243, 255, 255);
    }
    .cards-columns{
        font-size: large;
        
        font-family: 'Times New Roman';
    }
</style>
 
<div class="container ">
        
    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 42rem; border:5px black solid">
            <img class="card-img-top" src="{%static  'result.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <h3 class="card-title">Score: {{score}}</h5>
 
               <h3> <p class="card-text">Percentage: {{percent}}%</p> </h3>
              <h3>  <p class="card-text">Time Taken: {{time}} Minutes</p> </h3>

               <h3><p class="card-text">Correct answers: {{correct}}</p>  </h3>
                <h3><p class="card-text">Incorrect answers: {{wrong}}</p> </h3>

               <h3> <p class="card-text">Total questions: {{total}}</p> </h3>
                <hr >
                {% for q in users %}
                <h3>{{q.Question}}</h3>
                <br>
                <br>
              <p>  A:{{q.A}} </p>
              <p>  B:{{q.B}} </p>
              <p>  C:{{q.C}} </p>
              <p>  D:{{q.D}} </p>
              <br>
              <br>
              <hr>
              <h4>CORRECT ANSWER</h4>
              <p>{{q.Answer}}</p>
<br>
<br>
<h3>ANSWER EXPLANATION </h3>
                {{q.Answer_expalanation}}
                <hr>
                {% endfor %}
                <h5>All the best for next quiz!</h5>
            </div>
        </div>
        
    </div>
 
</div>
 
{% endblock %}